name = "SIDISXSec"
uuid = "db2f9484-0a0b-410d-b12d-1b6aa968f6b6"
authors = ["Youjack <iamjasonlin@163.com>"]
version = "0.1.0"

[deps]
HCubature = "19dc6840-f33b-545b-b366-655c7e3ffd49"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
QEDFactorization = "34e6992a-37ee-4e99-8345-6cb11d70fa03"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TMDTools = "8201fa51-4a18-4976-9f36-97c149c1ad5a"
cLHAPDF = "633b9f2c-654d-4886-93c1-b219cb2e426c"
